// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOgC37AnOV776KaBb13vsf8UDo-Mm0IQ8',
    appId: '1:759128164756:web:9c73bd8b2af3574e516781',
    messagingSenderId: '759128164756',
    projectId: 'food-4cd22',
    authDomain: 'food-4cd22.firebaseapp.com',
    storageBucket: 'food-4cd22.appspot.com',
    measurementId: 'G-NSSP6PR5H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo6ogh8Y4fxuVYfRPlg8C54sY4vb9x1JM',
    appId: '1:759128164756:android:c5c2e3f3ba8a606c516781',
    messagingSenderId: '759128164756',
    projectId: 'food-4cd22',
    storageBucket: 'food-4cd22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj6DspyoMgO_tGmR7K-kUZVeQFfBk00Qo',
    appId: '1:759128164756:ios:1a52f903339f1deb516781',
    messagingSenderId: '759128164756',
    projectId: 'food-4cd22',
    storageBucket: 'food-4cd22.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj6DspyoMgO_tGmR7K-kUZVeQFfBk00Qo',
    appId: '1:759128164756:ios:466573186637cbd9516781',
    messagingSenderId: '759128164756',
    projectId: 'food-4cd22',
    storageBucket: 'food-4cd22.appspot.com',
    iosBundleId: 'com.example.food.RunnerTests',
  );
}
